Domain definition #7
OpenFuturePlatform/open-state pull request #11
Opened 2020-08-27 10:04 UTC by trenatov

#7 Domain definition

@ruslanys Noticed that Github hides the last empty lines))

2020-08-27 10:08 UTC, layko-andrey commented on build.gradle
> -    implementation('org.springframework.boot:spring-boot-starter-security')
Need to remove commented code

2020-08-27 10:28 UTC, trenatov commented on build.gradle
> -    implementation('org.springframework.boot:spring-boot-starter-security')
done

2020-08-27 14:47 UTC, ruslanys requested changes

2020-08-27 14:47 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/controller/WalletController.kt
> +    suspend fun save(@RequestBody request: SaveWalletRequest): WalletDto {
Validation is missing. `@Valid`

2020-08-27 14:47 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/controller/domain/dto/WalletDto.kt
> +package io.openfuture.state.controller.domain.dto
1. Wrong package name. -> `io.openfuture.controller.dto`. Domain and DTO are incompatible. 
1. I would recommend defining DTO classes as well as Request/Response wrappers in the controllers that are using them. For sure, if the DTO is wide-spread it doesn't make sense. However, in most cases, DTO needs to be defined within a specific controller that handles it.

2020-08-27 14:47 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/controller/domain/dto/WalletDto.kt
> +package io.openfuture.state.controller.domain.dto
So, Define that `WalletDto` as an inner static class of `WalletController`. Because there is the only place when we are using it so fat.

2020-08-27 14:47 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/controller/domain/dto/WalletDto.kt
> +data class WalletDto(
Wrong validation. When a user will send you `NULL` for `id` or `address` you will not show a proper message. The message would be from Kotlin type validation.

For all DTOs, Requests wrappers you always have to define all properties as nullable and annotate them with validation annotations like `@NotNull` and `@NotEmpty` and use `@Valid` in the controller.
If the validation passed, you can be sure fields are not null and a user will get a proper status code and the error message.

2020-08-27 14:47 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/controller/domain/request/SaveWalletRequest.kt
> +package io.openfuture.state.controller.domain.request
The same for WalletDto:
1. Move to the Controller definition
1. Nullable properties + javax.valiation annotations

2020-08-27 14:47 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/mapper/WalletMapper.kt
> +interface WalletMapper {
Never (almost) for Kotlin

2020-08-27 14:47 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/mapper/WalletMapperImpl.kt
> +    override fun toWalletDto(wallet: Wallet): WalletDto {
Never.

Instead, you have to use DTO Constructor: `WalletDto(wallet)`.
Or extension functions maximum.

Mappers are from evil. Always.

2020-08-27 14:47 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/model/Transaction.kt
> +package io.openfuture.state.model
the package name is wrong. `model` -> `domain`.

2020-08-27 14:47 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/model/Wallet.kt
> +package io.openfuture.state.model
`model` -> `domain`

2020-08-27 14:47 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/model/Wallet.kt
> +        val id: ObjectId = ObjectId(),
all parameters with a default value are going at the bottom

2020-08-27 14:47 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/repository/WalletRepository.kt
> +interface WalletRepository : ReactiveMongoRepository<Wallet, String> {
Annotation `@Repository` is missing

2020-08-27 14:47 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/service/WalletService.kt
> +    suspend fun save(request: SaveWalletRequest): WalletDto
The only controller operates with DTO, Request, and Response. 
Service never care about that.

So, here should be the following signature:

```
suspend fun save(address: String, webhook: String): Wallet
```

2020-08-27 14:47 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/service/WalletService.kt
> +    suspend fun save(request: SaveWalletRequest): WalletDto
Sometimes, when there are a lot of arguments, it makes sense to pass the whole request object (and it is not prohibited):

```
suspend fun save(request: SaveWalletRequest): Wallet
```

However, service never response with DTO. And having a small number of parameters is clearer than passing FE Request.

2020-08-27 14:47 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/service/WalletServiceImpl.kt
> +class WalletServiceImpl(private val walletRepository: WalletRepository,
Never align arguments in such a way (https://yadi.sk/i/7mDfTtR3TXLyuw).
In Kotlin it will be:
```
Service(
  val a: A,
  val b: B
)
```

2020-08-27 14:47 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/service/WalletServiceImpl.kt
> +class WalletServiceImpl(private val walletRepository: WalletRepository,
`WalletServiceImpl` -> `DefaultWalletService`

2020-08-27 14:47 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/service/WalletServiceImpl.kt
> +                lastUpdateDate = LocalDateTime.now(),
Should have a default value in the constructor.

2020-08-27 14:47 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/service/WalletServiceImpl.kt
> +                transactions = emptySet()
Default value

2020-08-27 14:47 UTC, ruslanys commented on src/test/kotlin/io/openfuture/state/base/ControllerTests.kt
> +    protected lateinit var om: ObjectMapper
Do not cut the words: `om` -> `objectMapper`

2020-08-27 14:47 UTC, ruslanys commented on src/test/kotlin/io/openfuture/state/util/DummyData.kt
> +fun createDummyWalletDto(
Not sure you need it. `WalletDto(createDummyWallet())`

2020-08-27 14:47 UTC, ruslanys commented on src/test/kotlin/io/openfuture/state/util/DummyData.kt
> +fun createDummySaveWalletRequest(address: String = "address",
Invalid formatting

2020-08-27 17:09 UTC, ruslanys requested changes

2020-08-27 17:09 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/controller/WalletController.kt
> +            @field:NotNull
Try to put them on the same line

2020-08-27 17:09 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/controller/ExceptionHandler.kt
> +    data class ErrorDto(
ErrorDto exactly is an example of a wide-spread model, so, don't inline it here

2020-08-27 17:09 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/service/DefaultWalletService.kt
> +                address = address,
Why you specify fields name here?

2020-08-27 17:09 UTC, ruslanys commented on src/test/kotlin/io/openfuture/state/controller/ExceptionHandlerTest.kt
> +        val errorDto = ExceptionHandler.ErrorDto(HttpStatus.NOT_FOUND.value(), exception.message)
Move out the ErrorDto

2020-08-27 18:19 UTC, ruslanys requested changes

2020-08-27 18:19 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/controller/ExceptionHandler.kt
> +    data class FieldErrorDto(
Bud, this DTO has to be moved as well! What are the reasons to hold it here. The only ErrorDto is using it

2020-08-27 18:19 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/controller/WalletController.kt
> +    suspend fun save(@RequestBody @Valid request: SaveWalletRequest): WalletDto {
now it looks much better, but let's define as a styleguide to put Valid prior to RequestBody

2020-08-27 18:19 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/controller/WalletController.kt
> +            val address: String,
yes, and property definition in the same line as well. 
And I belive NotBlank can cover NotEmpty. So, one of these is enough.

2020-08-27 18:19 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/controller/dto/ErrorDto.kt
>  )
field Error can be an inner static class of ErrorDto

2020-08-27 18:19 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/domain/Wallet.kt
> +        val id: ObjectId = ObjectId(),
also could be at the same line with property definition

2020-08-27 18:19 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/service/DefaultWalletService.kt
> +        wallet ?: throw NotFoundException("Wallet with address $address not found")
You should not mention wallet variable here

2020-08-27 18:56 UTC, ruslanys requested changes

2020-08-27 18:56 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/controller/ExceptionHandler.kt
> +        val fieldErrors = ex.bindingResult.fieldErrors.map { ErrorDto.FieldErrorDto(it.field, it.defaultMessage) }
Oh, sorry mate. I didn't see that we are preparing `FieldErrorDto` out of the `ErrorDto`. Then it makes sense to have an independent class `FieldErrorDto`.
Sorry again.

2020-08-27 18:56 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/service/DefaultWalletService.kt
> +        val wallet = walletRepository.findByAddress(address).awaitFirstOrNull()
```
val wallet = walletRepository.findByAddress(address).awaitFirstOrNull()
    ?: throw NotFoundException("Wallet not found")
```

2020-08-27 18:59 UTC, ruslanys requested changes

2020-08-27 18:59 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/controller/page/PageResponse.kt
> +package io.openfuture.state.controller.page
controller.dto

2020-08-27 18:59 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/controller/page/PageRequest.kt
> +package io.openfuture.state.controller.page
controller.dto

2020-08-27 19:02 UTC, ruslanys requested changes

2020-08-27 19:02 UTC, ruslanys commented on src/test/kotlin/io/openfuture/state/base/ControllerTests.kt
> +    protected lateinit var objectMapper: ObjectMapper
Well. Remove this.

2020-08-27 19:02 UTC, ruslanys commented on src/test/kotlin/io/openfuture/state/controller/WalletControllerTest.kt
> +                .json(objectMapper.writeValueAsString(walletDto))
You should not programmatically create JSONs. Instead, you need to have them as static files or inline json right here.
https://github.com/ruslanys/ifunny/blob/master/src/test/kotlin/me/ruslanys/ifunny/controller/api/FeedApiControllerTests.kt

2020-08-28 12:14 UTC, ruslanys requested changes

2020-08-28 12:14 UTC, ruslanys commented on src/test/kotlin/io/openfuture/state/controller/WalletControllerTest.kt
> +        """
trimIndent

2020-08-28 12:14 UTC, ruslanys commented on src/test/kotlin/io/openfuture/state/controller/WalletControllerTest.kt
> +                .json(json)
Inline the JSON right here

2020-08-28 12:14 UTC, ruslanys commented on src/test/kotlin/io/openfuture/state/controller/WalletControllerTest.kt
> +                .json(json)
inline json

2020-08-28 12:14 UTC, ruslanys commented on src/test/kotlin/io/openfuture/state/repository/WalletRepositoryTest.kt
> +
empty line

2020-08-28 17:27 UTC, ruslanys commented on src/test/kotlin/io/openfuture/state/controller/WalletControllerTest.kt
> +        {
What's wrong with this indent?

2020-08-28 20:30 UTC, ruslanys commented
Take a look at my final commit: https://github.com/OpenFuturePlatform/open-state/commit/526548c66ed675171534f5c37d132d958d91b3db.

And now you know how to write perfect code. At least in my opinion. :)
I hope you will not forget it soon and we will not repeat the same things.
Before any PR, make sure you have reviewed yourself a few times.

2020-08-28 20:31 UTC, ruslanys approved these changes

2020-08-28 20:31 UTC, merged