GitHub action test build jobs
OpenFuturePlatform/open-state pull request #14
Opened 2020-09-10 14:03 UTC by layko-andrey

2020-09-10 17:34 UTC, trenatov requested changes

2020-09-10 17:34 UTC, trenatov commented on .github/workflows/deploy.yml
> +          MONGO_INITDB_ROOT_PASSWORD:  open_state
format please

2020-09-10 20:02 UTC, ruslanys requested changes

2020-09-10 20:02 UTC, ruslanys commented on .github/workflows/deploy.yml
> +    branches: [ 2.x.x-REACTIVE ]
Is there a chance to take a look at the pipeline before the merge?

2020-09-10 20:02 UTC, ruslanys commented on .github/workflows/deploy.yml
> +    env:
I don't think we need to duplicate default values as we already have them in `application.properties` file.

2020-09-10 20:03 UTC, ruslanys commented on .github/workflows/deploy.yml
> +    branches: [ 2.x.x-REACTIVE ]
BTW, we have to run tests at all of the branches. We can do `build` on the protected branches (`master` / `2.x.x-REACTIVE`) and on PR (the section below)

2020-09-11 05:46 UTC, layko-andrey commented on .github/workflows/deploy.yml
> +    branches: [ 2.x.x-REACTIVE ]
No. We have to merge these changes to 2.x.x.Release to see lit of workflows and have ability to run it. Workflow not visible from pull request unfortunately.

2020-09-11 05:48 UTC, layko-andrey commented on .github/workflows/deploy.yml
> +    branches: [ 2.x.x-REACTIVE ]
I would check it, as far as I know GitHub has ability to run Actions on any selected branch

2020-09-11 05:48 UTC, layko-andrey commented on .github/workflows/deploy.yml
> +          MONGO_INITDB_ROOT_PASSWORD:  open_state
Fixed, thanks

2020-09-11 06:34 UTC, layko-andrey commented on .github/workflows/deploy.yml
> +    env:
But we can change it at any time according our needs. But workflow would be independent  of these cases and tests would run in own environment space.

2020-09-11 07:49 UTC, ruslanys commented on .github/workflows/deploy.yml
> +    env:
For the test cases, there is no need to do this. If we have specific parameters, we will define it here. Until it is the same as we have in the application.properties, there are no reasons to duplicate the code.

2020-09-11 07:49 UTC, ruslanys commented on .github/workflows/deploy.yml
> +    branches: [ 2.x.x-REACTIVE ]
For sure we can. You just need to define more (or even all) branches instead.

2020-09-11 07:58 UTC, layko-andrey commented on .github/workflows/deploy.yml
> +    branches: [ 2.x.x-REACTIVE ]
Ok, would be done

2020-09-11 07:58 UTC, layko-andrey commented on .github/workflows/deploy.yml
> +    env:
Would fix it

2020-09-17 15:10 UTC, ruslanys commented on .github/workflows/deploy.yml
> +name: Deploy Open State
Change the name

2020-09-17 15:16 UTC, ruslanys commented
1. Change the name of the Workflow
2. We have to start the pipelines on more then just 2.x.x-REACTIVE branch.
2.1. * (all branches): test
2.2. [protected branches] (master / 2.x.x-REACTIVE): all above, + build -> jar

2020-09-17 15:22 UTC, ruslanys commented
The next PR should:

! extend `build` with docker packaging

--

* deploy
* code coverage (codecov.io)

2020-09-18 06:12 UTC, layko-andrey commented on .github/workflows/deploy.yml
> +name: Deploy Open State
Fixed

2020-09-18 06:16 UTC, layko-andrey commented
> 1. Change the name of the Workflow
> 2. We have to start the pipelines on more then just 2.x.x-REACTIVE branch.
>    2.1. * (all branches): test
>    2.2. [protected branches] (master / 2.x.x-REACTIVE): all above, + build -> jar

2020-09-18 06:58 UTC, ruslanys approved these changes

2020-09-18 06:59 UTC, ruslanys approved these changes

2020-09-18 07:01 UTC, merged