03 webhook invocation
OpenFuturePlatform/open-state pull request #48
Opened 2021-04-01 16:38 UTC by layko-andrey

2021-04-05 13:13 UTC, trenatov submitted a review, later dismissed

2021-04-06 16:03 UTC, ruslanys requested changes

2021-04-06 16:03 UTC, ruslanys commented on build.gradle
> +    implementation('io.projectreactor:reactor-core')
It's already in-place

2021-04-06 16:03 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/config/RedisConfig.kt
> -
Do not remove the empty line

2021-04-06 16:03 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/domain/TransactionQueueTask.kt
> +        val transactionId: String = ""
Styleguide?

2021-04-06 16:03 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/domain/TransactionQueueTask.kt
> +        val transactionId: String = ""
remove default value

2021-04-06 16:03 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/extensions/Extensions.kt
> +fun LocalDateTime.toMillisDouble(): Double {
Remove

2021-04-06 16:03 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/repository/WalletQueueRedisRepository.kt
> +    suspend fun score(walletId: String): Mono<Double> {
Replace function. `isExists`?

2021-04-06 16:03 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/repository/WalletQueueRedisRepository.kt
> +    suspend fun score(walletId: String): Mono<Double> {
suspend fun <> Mono

2021-04-06 16:03 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/repository/WalletQueueRedisRepository.kt
> +    suspend fun walletsScheduledTo(toDate: LocalDateTime): Flux<String> {
Flow

2021-04-06 16:03 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/repository/WalletQueueRedisRepository.kt
> +    suspend fun walletsScheduledTo(toDate: LocalDateTime): Flux<String> {
!suspend

2021-04-06 16:03 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/service/DefaultWalletQueueService.kt
> +class DefaultWalletQueueService(
Refactor

2021-04-06 16:03 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/service/DefaultWebhookService.kt
> +        private val walletQueueService: WalletQueueService,
Remove service layer for this purpose.

2021-04-06 16:03 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/service/DefaultWebhookService.kt
> +        private val walletQueueService: WalletQueueService,
Merge these services into one redis repo

2021-04-06 16:03 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/service/DefaultWebhookService.kt
> +    override suspend fun walletsScheduledForNow(): List<String> {
Refactor.

1. Only one wallet
2. Method should check that score is less than now()
3. Return Wallet + Score
4. Optional argument score

2021-04-06 16:03 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/webhhok/DefaultWebhookExecutor.kt
> +class DefaultWebhookExecutor: WebhookExecutor {
We cannot merge it

2021-04-06 16:03 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/webhhok/WebhookProcessor.kt
> +    fun process() = GlobalScope.launch {
Replace `GlobalScope.launch` with `runBlocking`

2021-04-08 07:32 UTC, layko-andrey commented on src/main/kotlin/io/openfuture/state/extensions/Extensions.kt
> +fun LocalDateTime.toMillisDouble(): Double {
Done

2021-04-08 08:07 UTC, layko-andrey commented on src/main/kotlin/io/openfuture/state/webhhok/WebhookProcessor.kt
> +    fun process() = GlobalScope.launch {
Done

2021-04-08 08:08 UTC, layko-andrey commented on src/main/kotlin/io/openfuture/state/webhhok/DefaultWebhookExecutor.kt
> +class DefaultWebhookExecutor: WebhookExecutor {
Removed

2021-04-08 08:09 UTC, layko-andrey commented on src/main/kotlin/io/openfuture/state/service/DefaultWebhookService.kt
> +        private val walletQueueService: WalletQueueService,
Done

2021-04-08 08:11 UTC, layko-andrey commented on src/main/kotlin/io/openfuture/state/domain/TransactionQueueTask.kt
> +        val transactionId: String = ""
Done

2021-04-08 08:16 UTC, layko-andrey commented on src/main/kotlin/io/openfuture/state/repository/WalletQueueRedisRepository.kt
> +    suspend fun score(walletId: String): Mono<Double> {
Renamed to walletScode(). Returned valuewould be used for re-scheduling of wallet later

2021-04-08 13:48 UTC, layko-andrey commented on src/main/kotlin/io/openfuture/state/service/DefaultWebhookService.kt
> +    override suspend fun walletsScheduledForNow(): List<String> {
Done

2021-04-12 07:06 UTC, trenatov approved these changes

2021-04-12 17:21 UTC, ruslanys commented on src/main/kotlin/io/openfuture/state/domain/WalletIdentity.kt
>  )
now new line

2021-04-12 17:26 UTC, ruslanys approved these changes

2021-04-12 17:26 UTC, merged